import React, { Component } from "react";
import ScrollAnimation from "react-animate-on-scroll";

export default class Slide19 extends Component {
  render() {
    return (
      <div className="Contact__container" >
        <div className="slide-container slide-container3">
          
            <div className="data-container">
              <ScrollAnimation 
                animateIn="fadeInLeft"
                animateOut="fadeOut"
                duration={1.2}
                delay={1.5}
              >
                <div className="left-container">
                  <h5 class="white_para-head">50% of all fees generated on the platform are distributed to stakers and rewards pools on ETH, BSC and FTM.</h5>
                  <h5 class="white_para-head">25% of all platform fees will go to operating expenses and buyback of tokens.</h5>
                  <h5 class="white_para-head">25% all fees generated by the NFT platform go to QUAI DAO for Governance and Development. An Equivalent amount of eYe tokens are to be burned each month.</h5>
                </div>
              </ScrollAnimation>
              <ScrollAnimation 
                animateIn="fadeInRight"
                animateOut="fadeOut"
                duration={1.2}
                delay={1.5}
              >
                <div className="right-container">
                  <h1 className="grad-head-a" style={{fontSize: "10vh"}}>(eYe) Token Metrics</h1>
                  <h5 class="white_para-head">The eYe token is designed as a multi-chain cryptographic unit for Binance Smart Chain and Etherium blockchain networks that drives the MeDIA eYe platform. The eYe token serves as utility and rewards vehicle allowing token holders to purchase services, receive discounts, earn rewards and farm.</h5>
                </div>
              </ScrollAnimation>
            </div>
        </div>  
      </div>
    );
  }
}         